### ISSUE TITLE
In words.scss line 99

### ISSUE THREAD

**Issue by samzeng** [dougblack/dougblack.io#3]
``` scss
pre {
    ...
    font-style: bold;
    ...
}
```

`font-style: normal | italic | oblique | inherit`

Do you want to set `font-weight: bold;` ?
